### ISSUE TITLE
centos 8: No package python-netaddr available

### ISSUE THREAD

**Issue by Sispheor** [bertvv/ansible-role-bind#117]
But python3-netaddr exists.

**Comment by blofeldthefish** [comment]
Hi there,

This issue has been addressed in PR #107, which is still open (not merged) because there is no automated test for CentOS 8, as yet.

If you look at https://github.com/bertvv/ansible-role-bind/pull/107/files, and change your local vars/Redhat.yml file to match the change shown in there, it will work.

I appreciate this is not ideal, and there is activity occurring in the background to refresh the test harnesses for this role, so that CentOS/RHEL 8 is a supported distribution, and then that code will be merged.

**Comment by bertvv** [comment]
The PR was merged an a new version will be released very soon (today, I hope)!

**Comment by Sispheor** [comment]
Thanks guys !
